Neoway's feature store blog post
NeowayLabs/neowaylabs.github.io pull request #30
Opened 2021-11-25 01:38 UTC by breno-costa

I'm writing this blog post about Neoway's Feature Store to show a little bit what we created internally for data scientists. Please review @NeowayLabs/ml-platform 

## How to run

```bash
make blog
```

2021-11-25 14:12 UTC, mfrata commented
@breno-costa Please put the text on grammarly. There are 15 suggestion on correctness 
![image](https://user-images.githubusercontent.com/15002208/143456570-6b7ff16a-3aba-4e10-b891-58315a8cc3db.png)

2021-11-26 14:06 UTC, breno-costa commented
> @breno-costa Please put the text on grammarly. There are 15 suggestion on correctness ![image](https://user-images.githubusercontent.com/15002208/143456570-6b7ff16a-3aba-4e10-b891-58315a8cc3db.png)

It's done!

2021-11-26 14:42 UTC, rootshell2 commented
como eu saio dessa porra?
Best Regards,

Alfredo Tomio Junior
+31 684431787


On Fri, 26 Nov 2021 at 15:06, Breno Costa ***@***.***> wrote:

> @breno-costa <https://github.com/breno-costa> Please put the text on
> grammarly. There are 15 suggestion on correctness [image: image]
> <https://user-images.githubusercontent.com/15002208/143456570-6b7ff16a-3aba-4e10-b891-58315a8cc3db.png>
>
> It's done!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NeowayLabs/neowaylabs.github.io/pull/30#issuecomment-980001651>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABGWUIHPBU5Y2QMTYGV7KM3UN6H5PANCNFSM5IXL54SQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-26 15:24 UTC, mfrata commented
@rootshell2 

![image](https://user-images.githubusercontent.com/15002208/143602542-75e87f10-e41a-4646-a247-9030ff345005.png)

2021-11-26 17:48 UTC, ryukinix approved these changes
@breno-costa LGTM

2021-11-26 17:48 UTC, ryukinix commented on _posts/2021-11-23-neoways-feature-store.md
> +> This blog post was written with the support of talented people who developed Neoway's Feature Store together with me, [Manoel Vilela](https://www.linkedin.com/in/lerax/) and [Matheus Frata](https:/
:cool:

2021-11-26 17:48 UTC, ryukinix commented on _posts/2021-11-23-neoways-feature-store.md
> +#### configuration.json
```suggestion
#### config.json
```
The name of file is `config.json`

2021-11-26 17:48 UTC, ryukinix commented on _posts/2021-11-23-neoways-feature-store.md
> +|         | build | lint | tests | transform | expectations | register | ingest | publish |
nice table

2021-11-29 13:16 UTC, mfrata requested changes

2021-11-29 19:25 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +#### configuration.json
fixed

2021-11-29 19:44 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +A data frame that was previously ingested can be published to the Datahub, and data will be available for consumers such as ElasticSearch, MongoDB, Neo4j, Big Query, and so on.
@mfrata replaced by kafka. datahub is only a alias for kafka.

2021-11-29 19:46 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +Let's see an example of how to use a dataset to make a simple transformation and create a new useful data frame using the dataset of company partners.
@mfrata That will be for another time. I can't record again.

2021-11-29 19:47 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +* Schema name cannot exceed 38 characters
@mfrata ok

2021-11-29 19:48 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +Once the schema is registered, you can ingest data frames into the Feature Store. You can use the method `fs.ingest()` to ingest a data frame into the feature store. The ingestion method is performed
@mfrata fixed

2021-11-29 19:50 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +Our Feature Store is fully integrated with the data platform, and this allows the interaction with data capabilities to perform tasks very easily, such as reading files from and writing files to the
@mfrata i'm talking about the data platform components on the paragraph.

reading files from and writing files to the data lake
registering schemas in the Schema API
producing data to Kafka
inserting records in PostgreSQL
indexing data in the Elastic Search

2021-11-29 20:01 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +This architecture can be easily extended to attend new use cases such as near real-time prediction using Kafka and Spark Streaming for generating stream features, but our business context still does
@mfrata spark structured streaming make things easier. It builds a dataframe from the kafka topics, and we can use the same transformation code for running using it as input.

![image](https://user-images.githubusercontent.com/35263725/143934339-4c0417e9-2a3c-4f07-a39c-742e776e5e0e.png)

Check out an example on my github: https://github.com/breno-costa/feature-store

2021-11-29 20:19 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +The [Airflow](https://airflow.apache.org/) is being used to schedule and run the pipeline on production. Both CI/CD runner and Airflow are responsible to launch spark jobs to a Kubernetes cluster, an
@mfrata transformers audit? :thinking: nope

2021-11-29 20:20 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +The [Airflow](https://airflow.apache.org/) is being used to schedule and run the pipeline on production. Both CI/CD runner and Airflow are responsible to launch spark jobs to a Kubernetes cluster, an
@mfrata i have decided to leave the audit out of this article. There is already a lot written in this article and it would be difficult to explain the audit in a few words.

2021-11-29 20:52 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +All of the above-mentioned benefits come with the cost of maintaining a new component in ML infrastructure. It's important to assess whether the return on investment in this component is worth it for
@mfrata i disagree for two reasons: 1) because the readers don't need an external context to understand my blog post, 2) I'm formalizing the problems and motivations to have a feature store for those who don't know.

2021-11-29 21:11 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +* Register: create a new curated schema and register it on the catalog
@mfrata i'm explain the schemas on section Schemas Rules Everything before to proceed with feature store details. This phrase is just stating "Register: create a new curated schema and register it on the catalog". 

Nobody needs to know schema striple to understand this phrase.

2021-11-29 21:34 UTC, breno-costa commented on _posts/2021-11-23-neoways-feature-store.md
> +The main internal components are described below.
@mfrata changed

2021-11-29 21:38 UTC, breno-costa commented
@mfrata thank you for your suggestions. Most of them I aggred and changed the blog post. Some I didn't agree and tried to clarify why. Let me know if you think it's enough to merge this branch.

2021-11-30 10:27 UTC, mfrata commented on _posts/2021-11-23-neoways-feature-store.md
> +The [Airflow](https://airflow.apache.org/) is being used to schedule and run the pipeline on production. Both CI/CD runner and Airflow are responsible to launch spark jobs to a Kubernetes cluster, an
I mispoke here. The second comment has nothing to do with the first hahahha. Anyway I agree

2021-11-30 10:48 UTC, mfrata approved these changes

2021-12-01 14:36 UTC, merged